name: full-deploy

on:
  push:
    branches: ["main"]
    # Run ONLY when infra changes
    paths:
      - 'infra/**'
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 156041402173.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPO: devsecops
  CLUSTER_NAME: devsecops
  K8S_NAMESPACE: devsecops

permissions:
  id-token: write
  contents: read

# Per-workflow concurrency → won't cancel fast-deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  infra-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Terraform (plan + apply)
      - name: Configure AWS (assume Terraform role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::156041402173:role/devsecops-terraform-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=infra init -upgrade

      - name: Terraform Validate
        run: terraform -chdir=infra validate

      - name: Terraform Plan
        run: terraform -chdir=infra plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve tfplan

      # App: tests + scan + build + push
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests (skip if no tests)
        run: |
          . venv/bin/activate
          python -m pip install -q pytest || true
          if [ -d tests ] || [ -d test ]; then
            python -m pytest -q
          else
            echo "No tests/ directory found. Skipping tests."
          fi

      - name: Security scan (bandit) (skip if no app dir)
        run: |
          . venv/bin/activate
          python -m pip install -q bandit || true
          if [ -d app ]; then
            bandit -r app -ll || true
          else
            echo "No app/ directory found. Skipping bandit scan."
          fi

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image (tag = commit SHA)
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

      # Deploy to EKS
      - name: Install kubectl
        run: |
          curl -sL https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl -o kubectl
          install -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client=true

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"

      - name: Apply manifests & set image to SHA
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl -n "$K8S_NAMESPACE" set image deploy/python-app \
            python-app=$ECR_REGISTRY/$ECR_REPO:${{ github.sha }}

      - name: Wait for rollout
        run: |
          kubectl -n "$K8S_NAMESPACE" rollout status deploy/python-app --timeout=180s
